"""First revision

Revision ID: d4867f3a4c0a
Revises: 
Create Date: 2019-04-17 13:53:32.978401
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d4867f3a4c0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply first migration: create user and item tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create user table
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("full_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=True),
    )
    op.create_index("ix_user_email", "user", ["email"], unique=True)
    op.create_index("ix_user_full_name", "user", ["full_name"])
    op.create_index("ix_user_id", "user", ["id"])

    # Create item table
    op.create_table(
        "item",
        sa.Column("id", sa.Integer(), primary_key=True, nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), sa.ForeignKey("user.id"), nullable=True),
    )
    op.create_index("ix_item_title", "item", ["title"])
    op.create_index("ix_item_description", "item", ["description"])
    op.create_index("ix_item_id", "item", ["id"])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert first migration: drop item and user tables."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop item table and indexes
    op.drop_index("ix_item_title", table_name="item")
    op.drop_index("ix_item_description", table_name="item")
    op.drop_index("ix_item_id", table_name="item")
    op.drop_table("item")

    # Drop user table and indexes
    op.drop_index("ix_user_email", table_name="user")
    op.drop_index("ix_user_full_name", table_name="user")
    op.drop_index("ix_user_id", table_name="user")
    op.drop_table("user")
    
    # ### end Alembic commands ###
